// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// dmxa_rx //
// ------- //

#define dmxa_rx_wrap_target 0
#define dmxa_rx_wrap 5
#define dmxa_rx_pio_version 0

static const uint16_t dmxa_rx_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x2020, //  1: wait   0 pin, 0
    0xea27, //  2: set    x, 7                   [10]
    0x4001, //  3: in     pins, 1
    0x0643, //  4: jmp    x--, 3                 [6]
    0x4001, //  5: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmxa_rx_program = {
    .instructions = dmxa_rx_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = dmxa_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dmxa_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmxa_rx_wrap_target, offset + dmxa_rx_wrap);
    return c;
}
#endif
