// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// dmxrdm_tx //
// --------- //

#define dmxrdm_tx_wrap_target 0
#define dmxrdm_tx_wrap 4
#define dmxrdm_tx_pio_version 0

static const uint16_t dmxrdm_tx_program_instructions[] = {
            //     .wrap_target
    0x9fa0, //  0: pull   block           side 1 [7]
    0xff27, //  1: set    x, 7            side 1 [7]
    0xb742, //  2: nop                    side 0 [7]
    0x6601, //  3: out    pins, 1                [6]
    0x0043, //  4: jmp    x--, 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmxrdm_tx_program = {
    .instructions = dmxrdm_tx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = dmxrdm_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dmxrdm_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmxrdm_tx_wrap_target, offset + dmxrdm_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

