// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// dmxrdm_rx //
// --------- //

#define dmxrdm_rx_wrap_target 0
#define dmxrdm_rx_wrap 4
#define dmxrdm_rx_pio_version 0

static const uint16_t dmxrdm_rx_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x2020, //  1: wait   0 pin, 0
    0xea27, //  2: set    x, 7                   [10]
    0x4001, //  3: in     pins, 1
    0x0643, //  4: jmp    x--, 3                 [6]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dmxrdm_rx_program = {
    .instructions = dmxrdm_rx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = dmxrdm_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dmxrdm_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmxrdm_rx_wrap_target, offset + dmxrdm_rx_wrap);
    return c;
}
#endif

